version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nextgen_production_db
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_5ORFjmtxp8AK
      POSTGRES_DB: neondb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nextgen_production_backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:production_password_secure@db:5432/nextgen_crm_db?schema=public"
      PORT: 5000
      CLIENT_URL: "http://localhost:5173/"
      JWT_SECRET: "wjebjhedbfklklwejdfkjwbeedfj"
      JWT_EXPIRES_IN: "72h"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: 587
      SMTP_USER: "yatneshpuranik@gmail.com"
      SMTP_PASS: "jtrsbclgttjbnzvh"
      EMAIL_FROM: '"NextGen ERP Support" <yatneshpuranik@gmail.com>'
      SYSTEM_ALERT_EMAIL: "yatneshpuranik@gmail.com"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextgen_production_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  pgdata:
    driver: local
